from auxilio.path import ROOT_PATH, join_paths

# Paths
CAMINHO_ICONE = join_paths(ROOT_PATH, 'recursos', 'imagens', 'icone.png')

# Janela principal
ALTURA_DA_JANELA = 400
LARGURA_DA_JANELA = 700
ALTURA_BOTAO_CORRIGIR = 50
ALTURA_BOTAO_PROCURAR = 30

# Widgets filhos
ALTURA_CAIXA_COM_OS_CAMINHOS = 60
LARGURA_MAXIMA_LABEL_CAMINHO = 400
ALTURA_BOTAO_REMOVER = 30
LARGURA_BOTAO_REMOVER = 100
TAMANHO_FONTE_LABEL = 14
