name: CI (lint + testes + build)

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - "*"

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - name: Setup Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalando Poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.2.2
        virtualenvs-create: true
        virtualenvs-in-project: true

    - name: Instalando dependências
      run: poetry install

    - name: Executando Lint
      run: |
        source $VENV
        pylint --rcfile=.pylintrc --output-format=colorized --fail-under=6.5 -r=y src

  build:
    name: Build app
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          # ubuntu-22.04 Desativado até resolver o erro de dependência
          - os: macos-latest
          - os: windows-2022
    steps:
      - name: Checkout na Branch
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Instalar dependências para ${{ matrix.config.os }}
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          python -m poetry install

      - name: Build App com PyInstaller no ${{ matrix.config.os }}
        run: python -m poetry run pyinstaller corretor.spec
    
  tests:
    name: Executando testes unitários
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - name: Setup Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalando Poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.2.2
        virtualenvs-create: true
        virtualenvs-in-project: true

    - name: Instalando dependências
      run: poetry install

    - name: Run pytest
      run: |
        source $VENV
        pytest src
