name: Criar Executáveis

on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  build:
    name: Build app
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          # ubuntu-22.04 Desativado até resolver o erro de dependência
          - os: macos-latest
          - os: windows-2022
    steps:
      - name: Checkout na Branch
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Instalar dependências para ${{ matrix.config.os }}
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          python -m poetry install

      - name: Build App com PyInstaller no ${{ matrix.config.os }}
        run: python -m poetry run pyinstaller corretor.spec

      - name: Renomear o Diretório de Build
        run: mv ./dist ./dist-${{ matrix.config.os }}

      - name: Upload resultado do Job ${{ matrix.config.os }}
        uses: actions/upload-artifact@v3
        with:
          name: corretor-pyinstaller-artifact
          path: ./dist*

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: corretor-pyinstaller-artifact

      - name: Zippar arquivos Windows
        run: zip -r corretor_windows.zip dist-windows-*

      # Desativado até resolver o erro de dependência
      # - name: Zippar arquivos Ubuntu
      #   run: zip -r corretor_ubuntu.zip dist-ubuntu-*

      - name: Zippar arquivos MacOS
        run: zip -r corretor_macos.zip dist-macos-*

      - name: Criar Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: |
            corretor_windows.zip
            corretor_macos.zip
          # corretor_ubuntu.zip    Desativado até resolver o erro de dependência
