name: Lint PR

on:
  pull_request:
    branches:
      - main

jobs:
  main:
    name: Valida título da PR
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
