name: CI(Lint)

on:
  pull_request:
    branches:
      - main


jobs:
  lint:
    name: Lint no Código
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - name: Setup Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalando Poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.2.2
        virtualenvs-create: true
        virtualenvs-in-project: true

    - name: Instalando dependências
      run: poetry install

    - name: Executando Lint
      run: |
        source $VENV
        pylint --rcfile=.pylintrc --output-format=colorized --fail-under=6.5 -r=y src
