name: CI(Tests)

on:
  pull_request:
    branches:
      - main


jobs:
  tests-unit:
    name: Testes Unitários
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - name: Setup Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalando Poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.2.2
        virtualenvs-create: true
        virtualenvs-in-project: true

    - name: Instalando dependências
      run: poetry install

    - name: Run pytest
      run: |
        source $VENV
        pytest